theme: jekyll-theme-hacker

title: Personal blog
description: "Starting a new project"
markdown: kramdown
author:
  name: "Pablo Ramirez"
  email: "prmzs89@hotmail.com"

source: .
destination: ./_site

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "PabloRS"
year : "2022"
